services:
  # the client is hosted separately, it is excluded from the server VM

  server:
    image: zyphex/gogosumo-server
    ports:
      - 5333:8080
    depends_on:
      - flyway

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -schemas=public -baselineOnMigrate=false -connectRetries=60 migrate
    volumes:
      - ./GoGoSumo.Database/Migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./deploy/env.prod.db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
