services:
  server:
    image: zyphex/gogosumo-server
    environment:
      ASPNETCORE_HTTPS_PORTS: 443
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_CERT_PASSWORD}
      CUSTOMCONNSTR_PostgresConnection: ${POSTGRES_CONNECTION_STRING}
    volumes:
      - ./deploy/cert.pfx:/https/cert.pfx
    ports:
      - 443:443
    depends_on:
      - flyway

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -schemas=public -baselineOnMigrate=false -connectRetries=60 migrate
    volumes:
      - ./GoGoSumo.Database/Migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
