name: Build and deploy ASP.Net Core app to Azure Web App - GoGoSumoApi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        working-directory: ./github_docker_deploy
        run: dotnet build --configuration Release

      - name: Run Tests
        working-directory: ./github_docker_deploy
        run: dotnet test


  publish_to_docker:
    needs: build_and_test:
    runs-on: ubuntu-latest
    steps:
    -  name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    -  name: Build and push client
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: zyphex/gogosumo/gogosumo-client:latest
      
    -  name: Build and push server
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: zyphex/gogosumo/gogosumo-server:latest
 
#  TODO: WIP
  # create_new_container:
  #   needs: publish_to_docker
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: executing remote ssh commands using private key
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USERNAME }}
  #       key: ${{ secrets.SSH_KEY }}
  #       script: |
  #         sudo docker rm -f $(docker ps -aq -f name=gogosumo-server)
  #         sudo docker rmi $(docker images | grep 'zyphex/gogosumo' | awk '{print $3}')
  #         wget https://raw.githubusercontent.com/DillonWall/GoGoSumo/main/compose.yml
  #         docker pull zyphex/gogosumo
  #         sudo docker compose up -d