name: Server - Build and deploy ASP.Net Core app to VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: Build with dotnet
        working-directory: ./GoGoSumo.Server
        run: dotnet build --configuration Release

      - name: Run Tests
        working-directory: ./GoGoSumo.Server
        run: dotnet test

  publish_to_docker:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zyphex/gogosumo-server:latest

  deploy_container_to_vm:
    needs: publish_to_docker
    runs-on: self-hosted
    environment:
      name: "Production-Server"
    steps:
      - name: Update repo on VM and Docker compose up
        run: |
            cd ~/GoGoSumo
            git fetch --all
            git reset --hard origin/main
            docker compose -f compose.prod.yml --env-file ./deploy/.env.prod pull
            docker compose -f compose.prod.yml --env-file ./deploy/.env.prod up -d
